---
- include: staging_wsgi_files.yml
  tags: non-development

- include: apparmor_complain.yml
  tags: non-development,aa-complain

- include: dev_setup_xvfb_for_functional_tests.yml

- include: disable_mprotect_ff_plugin_container.yml
