---
- name: update apt package lists
  apt: update_cache=yes

- name: install apt package deps for dev environment
  apt: pkg="{{ item }}" state=latest
  with_items: dev_deps

- name: create the pypi.python.org local cert directory
  file: path=/usr/local/share/ca-certificates/pypi.python.org state=directory owner=root mode=2755

- name: install the pypi certificate
  copy: src=./pypi.crt dest=/usr/local/share/ca-certificates/pypi.python.org/pypi.crt owner=root mode=0644 force=yes

- name: install pip dependencies for securedrop
  pip: requirements="{{ securedrop_pip_requirements }}" extra_args="--cert /usr/local/share/ca-certificates/pypi.python.org/pypi.crt"

- name: set SECUREDROP_ENV in bashrc
  lineinfile:
    dest: /home/{{ securedrop_user }}/.bashrc
    state: present
    insertafter: EOF
    line: "export SECUREDROP_ENV=dev"
